plugins:
  - jekyll-sitemap

# SEO Stuff
author: salif
title: Блогът на Салиф
description: Блог за програмиране, технологии, изкуствени езици и всичко останало.
lang: bg
locale: bg_BG
url: "https://blog.salif.eu"
git_web_base: https://github.com/salif/blog.salif.eu/blob/HEAD/
baseurl: ""
permalink: /:categories/:title/

# RSS feeds
feed:
  posts_limit: 20
