plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives

title: "Блогът на Салиф"
description: "Блог за програмиране, изкуствени езици и всичко останало. #nobridge"
lang: bg
locale: bg_BG
url: "https://blog.salif.eu"
git_web_base: "https://github.com/salif/blog.salif.eu/blob/HEAD/"
baseurl: ""
permalink: /:categories/:title/
goatcounter_code: "blosaleu"
translate_code: "blog-salif-eu"
disqus_code: "blog-salif-eu"
author:
  name: Салиф Мехмед
  email: mail@salif.eu
  url: https://salif.eu/bg
  uri: https://salif.eu/bg

feed:
  disable_in_development: true
  posts_limit: 20
  categories:
    - 0

jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/:name/'
